version: '3'

services: 

  lab:
    container_name: lab 
    build: 
      context: .
      dockerfile: Dockerfile      
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./projects:/home/jovyan/work
