version: '3'

services: 

  my_lab:
    container_name: my_lab 
    image: 'jupyter/base-notebook'
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./projects:/home/jovyan/work
